package md.customs.calculator.presentation.util

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage { RO, EN, RU }

object LanguageManager {
    var currentLanguage by mutableStateOf(AppLanguage.RO)
}

object AppStrings {
    private val ro = mapOf(
        "app_title" to "Calculator Vamal",
        "product_name" to "Nume Produs (opțional)",
        "parcel_value" to "Valoare Colet",
        "shipping_cost" to "Cost Livrare",
        "currency" to "Valuta",
        "delivery_company" to "Companie Livrare (opțional)",
        "tracker_id" to "Tracker ID (opțional)",
        "category" to "Categoria Produsului",
        "reset" to "Resetează",
        "calculate" to "Calculează",
        "delete" to "Șterge",
        "save_history" to "Salvează în Istoric",
        "july_2026_rules" to "Aplică noile reguli vamale (1 Octombrie 2026)",
        "law_description" to "",
        "read_details" to "Citește detalii despre lege →",
        "error_parcel_value" to "Valoarea coletului trebuie să fie mai mare ca 0.",
        "scutire_title" to "Scutire aplicată",
        "total_payment" to "Total de plată:",
        "applied_july_2026" to "Legea 1 Octombrie 2026",
        "tracker" to "Tracker",
        "follow" to "Urmărește",
        "result_title" to "Rezultat Calcul",
        "base_calc" to "Baza de calcul (MDL)",
        "duty_tax" to "Taxă Vamală",
        "vat_tax" to "TVA (20%)",
        "proc_fee" to "Taxă proceduri vamale",
        "read_law_detailed" to "Citește detalii despre lege",
        "history_title" to "Istoric Calcule",
        "back" to "Înapoi",
        "no_saved_calculations" to "Nu există calcule salvate.",
        "product_label" to "Produs",
        "category_label" to "Categorie",
        "delivery_label" to "Livrare",
        "cat_phones" to "Telefoane Mobile (0%)",
        "cat_laptops" to "Laptopuri, PC (0%)",
        "cat_auto" to "Piese auto (10%)",
        "cat_shoes" to "Încălțăminte (10%)",
        "cat_clothes" to "Haine (15%)",
        "cat_cosmetics" to "Cosmetice (15%)",
        "cat_toys" to "Jucării (0%)",
        "cat_supplements" to "Suplimente alimentare (10%)",
        "cat_appliances" to "Electrocasnice (15%)",
        "cat_other" to "Altele (10%)",
        // New UI Keys
        "section_product" to "1. Produs / Categorie",
        "section_financials" to "2. Costuri & Transport",
        "current_law" to "Legea Curentă",
        "exemption_msg" to "Scutire aplicată: Coletele cu o valoare de până la 150 EUR sunt scutite de taxe vamale și TVA.",
        "disclaimer_title" to "Informații Importante & Surse",
        "disclaimer_text" to "Această aplicație NU reprezintă o entitate guvernamentală și NU este afiliată cu Serviciul Vamal al RM sau Guvernul RM.",
        "source_customs_label" to "Serviciul Vamal RM (Trimiteri Poștale)",
        "source_legis_label" to "Codul Vamal al RM (Legis.md)",
        "source_bnm_label" to "Banca Națională a Moldovei (BNM)"
    )

    private val en = mapOf(
        "app_title" to "Customs Calculator",
        "product_name" to "Product Name (optional)",
        "parcel_value" to "Parcel Value",
        "shipping_cost" to "Shipping Cost",
        "currency" to "Currency",
        "delivery_company" to "Delivery Company (optional)",
        "tracker_id" to "Tracker ID (optional)",
        "category" to "Product Category",
        "reset" to "Reset",
        "calculate" to "Calculate",
        "delete" to "Delete",
        "save_history" to "Save to History",
        "july_2026_rules" to "Apply new customs rules (October 1, 2026)",
        "law_description" to "",
        "read_details" to "Read details about the law →",
        "error_parcel_value" to "Parcel value must be greater than 0.",
        "scutire_title" to "Exemption applied",
        "total_payment" to "Total payable:",
        "applied_july_2026" to "October 1, 2026 Law",
        "tracker" to "Tracker",
        "follow" to "Track",
        "result_title" to "Calculation Result",
        "base_calc" to "Calculation Base (MDL)",
        "duty_tax" to "Customs Duty",
        "vat_tax" to "VAT (20%)",
        "proc_fee" to "Customs Procedure Fee",
        "read_law_detailed" to "Read details about the law",
        "history_title" to "Calculation History",
        "back" to "Back",
        "no_saved_calculations" to "No saved calculations.",
        "product_label" to "Product",
        "category_label" to "Category",
        "delivery_label" to "Delivery",
        "cat_phones" to "Mobile Phones (0%)",
        "cat_laptops" to "Laptops, PC (0%)",
        "cat_auto" to "Auto Parts (10%)",
        "cat_shoes" to "Shoes (10%)",
        "cat_clothes" to "Clothes (15%)",
        "cat_cosmetics" to "Cosmetics (15%)",
        "cat_toys" to "Toys (0%)",
        "cat_supplements" to "Supplements (10%)",
        "cat_appliances" to "Appliances (15%)",
        "cat_other" to "Other (10%)",
        // New UI Keys
        "section_product" to "1. Product / Category",
        "section_financials" to "2. Costs & Shipping",
        "current_law" to "Current Law",
        "exemption_msg" to "Exemption applied: Parcels valued up to 150 EUR are exempt from customs duties and VAT.",
        "disclaimer_title" to "Important Info & Sources",
        "disclaimer_text" to "This app DOES NOT represent a government entity and is NOT affiliated with Customs Service or Government of Moldova.",
        "source_customs_label" to "Customs Service of Moldova (Postal Items)",
        "source_legis_label" to "Customs Code of Moldova (Legis.md)",
        "source_bnm_label" to "National Bank of Moldova (Exchange Rates)"
    )

    private val ru = mapOf(
        "app_title" to "Таможенный Калькулятор",
        "product_name" to "Название товара (опционально)",
        "parcel_value" to "Стоимость посылки",
        "shipping_cost" to "Стоимость доставки",
        "currency" to "Валюта",
        "delivery_company" to "Служба доставки (опционально)",
        "tracker_id" to "Трекер ID (опционально)",
        "category" to "Категория товара",
        "reset" to "Сбросить",
        "calculate" to "Рассчитать",
        "delete" to "Удалить",
        "save_history" to "Сохранить в историю",
        "july_2026_rules" to "Применить новые правила (1 Октября 2026)",
        "law_description" to "",
        "read_details" to "Подробнее о законе →",
        "error_parcel_value" to "Стоимость посылки должна быть больше 0.",
        "scutire_title" to "Освобождение применено",
        "total_payment" to "Итого к оплате:",
        "applied_july_2026" to "Закон 1 Октября 2026",
        "tracker" to "Трекер",
        "follow" to "Отследить",
        "result_title" to "Результат расчета",
        "base_calc" to "База расчета (MDL)",
        "duty_tax" to "Таможенная пошлина",
        "vat_tax" to "НДС (20%)",
        "proc_fee" to "Таможенные процедуры",
        "read_law_detailed" to "Подробнее о законе",
        "history_title" to "История Расчетов",
        "back" to "Назад",
        "no_saved_calculations" to "Нет сохраненных расчетов.",
        "product_label" to "Продукт",
        "category_label" to "Категория",
        "delivery_label" to "Доставка",
        "cat_phones" to "Мобильные телефоны (0%)",
        "cat_laptops" to "Ноутбуки, ПК (0%)",
        "cat_auto" to "Автозапчасти (10%)",
        "cat_shoes" to "Обувь (10%)",
        "cat_clothes" to "Одежда (15%)",
        "cat_cosmetics" to "Косметика (15%)",
        "cat_toys" to "Игрушки (0%)",
        "cat_supplements" to "Пищевые добавки (10%)",
        "cat_appliances" to "Бытовая техника (15%)",
        "cat_other" to "Другое (10%)",
        // New UI Keys
        "section_product" to "1. Продукт / Категория",
        "section_financials" to "2. Стоимость и доставка",
        "current_law" to "Действующий закон",
        "exemption_msg" to "Применяется освобождение: Посылки стоимостью до 150 евро освобождаются от таможенных пошлин и НДС.",
        "disclaimer_title" to "Важная информация и источники",
        "disclaimer_text" to "Это приложение НЕ представляет государственную структуру и НЕ связано с Таможенной службой РМ.",
        "source_customs_label" to "Таможенная служба РМ (Почтовые отправления)",
        "source_legis_label" to "Таможенный кодекс РМ (Legis.md)",
        "source_bnm_label" to "Национальный банк Молдовы (Курсы валют)"
    )

    private val translations = mapOf(
        AppLanguage.RO to ro,
        AppLanguage.EN to en,
        AppLanguage.RU to ru
    )

    fun get(lang: AppLanguage, key: String): String {
        return translations[lang]?.get(key) ?: key
    }
}
